/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home/index`; params?: Router.UnknownInputParams; } | { pathname: `/home/productListScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/productListScreen` | `/productListScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/layout`; params?: Router.UnknownInputParams; } | { pathname: `/components/produtoCard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/navegacao` | `/navegacao`; params?: Router.UnknownInputParams; } | { pathname: `/home/navegacao`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home/index`; params?: Router.UnknownOutputParams; } | { pathname: `/home/productListScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/productListScreen` | `/productListScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/components/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/components/produtoCard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/navegacao` | `/navegacao`; params?: Router.UnknownOutputParams; } | { pathname: `/home/navegacao`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/home/index${`?${string}` | `#${string}` | ''}` | `/home/productListScreen${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/productListScreen${`?${string}` | `#${string}` | ''}` | `/productListScreen${`?${string}` | `#${string}` | ''}` | `/components/layout${`?${string}` | `#${string}` | ''}` | `/components/produtoCard${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/navegacao${`?${string}` | `#${string}` | ''}` | `/navegacao${`?${string}` | `#${string}` | ''}` | `/home/navegacao${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home/index`; params?: Router.UnknownInputParams; } | { pathname: `/home/productListScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/productListScreen` | `/productListScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/layout`; params?: Router.UnknownInputParams; } | { pathname: `/components/produtoCard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/navegacao` | `/navegacao`; params?: Router.UnknownInputParams; } | { pathname: `/home/navegacao`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
